### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by lookfirst** [plibither8/refined-hacker-news#121]
![2022-09-25 at 17 49 49](https://user-images.githubusercontent.com/85355/192157705-3c0881e1-74e5-4d58-bf48-781f91c9d8d5.png)

![2022-09-25 at 17 50 23](https://user-images.githubusercontent.com/85355/192157719-1f3835d4-c8f6-462b-a84c-23e3d517b860.png)

**Comment by plibither8** [comment]
Hi @lookfirst, thanks for bringing this up! I too noticed it today, along with another bug regarding the positioning of the "favorite" link. I'll be looking into this and soon have an update ready. Thanks again :)

**Comment by lookfirst** [comment]
Yea, I just noticed that I can't 'favorite' or 'flag' comments any more.

Looking at the code in utils.js, I'd re-work the general logic at the arrows too... you're basically checking for it to be null after having tried to use it...

![2022-09-25 at 17 53 36](https://user-images.githubusercontent.com/85355/192157881-c8931664-c56c-40b7-81bd-f82180aaa29e.png)

**Comment by plibither8** [comment]
Good catch with that! Not shifting blame, but I recall those lines of code being part of someone else's PR -- should've tested it out better back then 😄.

The entire codebase is in serious need of a refactor, since the code basically represents my abilities and understanding of when I was in highschool xD. Hopefully I've matured enough since to make it more error-prone now, when I get a chance too. :)

**Comment by plibither8** [comment]
I've fixed this bug, along with a few other and pushed the update for review to the Chrome Webstore. It should be live in a couple of days.

**Comment by lookfirst** [comment]
@plibither8 No worries and no blame! Thanks for the fast action on things. Super appreciate it.
