### ISSUE TITLE
Extend Vertical Line on Parent Comments Thru Child Comments for Readability

### ISSUE THREAD

**Issue by andspenrob** [plibither8/refined-hacker-news#30]
The variable indent helps separate the parent-child hierarchy, but extending the left borders of the parents would help track threads even more clearly! If this is easy enough to implement, it would be a huge improvement to readability!

I mocked up an example in the attached image...
![Vertical Line Example](https://user-images.githubusercontent.com/51801119/59464224-b4f83e00-8ddc-11e9-9250-bbbe050bed80.png)

**Comment by plibither8** [comment]
Hey!

This is an enhancement that, during the extension development, I've tried to implement. I gave up after a while, realising that due to the non-nested nature of all the HTML elements in the comments, and the fact that they are using a `table`, it almost seems impossible.

If someone else can give me an idea on how to solve this issue, I'd be really happy, but as for now I'll have close this issue.

Thanks a lot once again, cheers!
