### ISSUE TITLE
Flag any comment from the comments page

### ISSUE THREAD

**Issue by nick-s-b** [plibither8/refined-hacker-news#62]
Hi,
Currently to flag a comment (for spam) you have to open the comment in the new page to reveal the 'flag' link. Could we have it so that you can flag a comment from the story's comment page itself? 
Thanks!

**Comment by plibither8** [comment]
Thanks for the idea, missed it somehow. Currently working on it, should push to production soon!

**Comment by plibither8** [comment]
Hey Nick, I was rethinking about this and what I am worried about is potential misuse of the button since it will be right in front of you, and you don't have to take an extra step to open comment's page - that acts as a sort of deterrent.

Nevertheless to make this feature a bit more inconspicuous, I've enabled it as a keyboard shortcut: if the item is "active" (using `J` and `K` keypresses to navigate arouns the comments), then you can press <kbd>Shift</kbd>+<kbd>X</kbd> to flag or unflag the comment.

What do you think?

**Comment by nick-s-b** [comment]
Flagging of stories is available on the front page of the site. Is it really that dangerous?
How about not making the module enabled by default and you'd have to enable it manually like some other modules? Remembering keystrokes is cumbersome.

**Comment by plibither8** [comment]
On second thought, I guess you are right - I forget that stories can be flagged from the front-page. I've added this directly to the comments now next to the "favorite" button, and also enabled the keyboard shortcut.

**Comment by nick-s-b** [comment]
Awesome! Thank you!
