### ISSUE TITLE
Feature request: mute users

### ISSUE THREAD

**Issue by jvzr** [plibither8/refined-hacker-news#65]
Hey Mihir / @plibither8 

I hope you're doing great. I was wondering if you were open to the idea of adding the ability to mute users? When muting a user, his/her comments would be collapsed by default.

I recognize that it is not necessarily a good thing to have, but I'd be willing to develop it like I did collapse-root-comment. Ofc I'd prefer you telling me what you think before I start

Best,
jerome

**Comment by plibither8** [comment]
Hi @jvzr! Great to see you back :)

I know this is a really late reply and I apologise for it.
The feature that you propose seems a tad bit unhealthy. Sure it might come in use sometimes, but it might just encourage the habit of seeing _who_ has posted the comment rather than _what_ they have posted.

Maybe you can fork the repo and work on the feature separately - I will be happy to provide any assistance over there too! I myself am using a customised RHN with features I have decided not to make public too :P

Cheers, Mihir
