### ISSUE TITLE
Highlighted comment text inserted as quoted text incorrectly

### ISSUE THREAD

**Issue by myfirstnameispaul** [plibither8/refined-hacker-news#67]
The add-on has the current behavior:

When a comment's text is highlighted, it will be included as quoted text with syntax

````
> *highlighted text is now italicized and the the > is only present on first line and does not appear again*
````

However, the more standard method of quoting a comment on HN is the following:

````
> Each block of text uses the > on the first line. There are no italics unless they were used in the quoted text.

> Additional blocks of text with > on the first line.
````

Can this be changed? It is very convenient to just highlight and click reply and it seems like it is already very close to being *perfect*.

**Comment by plibither8** [comment]
Hi :)

> the more standard method of quoting a comment on HN is the following

I've come to realise this too, however I thought at that moment that italicising the text gives it a more "quoted" feel since HN doesn't inherintly support quote styling.

What I can do is add this as an option in the popup window: the default action would be not to italice the text so it remains as is.
As for adding the ">" before additional blocks of text, completely agree. I'll add that feature.

Thanks for opening the issue, cheers!

**Comment by plibither8** [comment]
@myfirstnameispaul I've pushed the new, updated version to the Chrome Webstore and Mozilla Add-ons. It should appear publically in a short while.

**Comment by myfirstnameispaul** [comment]
Works perfectly in Firefox. Thank you.
