### ISSUE TITLE
Feature request: convert text surrounded by backticks to monospace.

### ISSUE THREAD

**Issue by sjuxax** [plibither8/refined-hacker-news#74]
Most developer-oriented sites will take text surrounded by backticks and make it an inline-monospace font with some highlighting, `like so`. I've always hated that HN doesn't have this and sometimes follow the convention anyway ([this comment](https://news.ycombinator.com/item?id=22774198), for example) in hopes that it would one day become part of the codebase. It'd be awesome if this extension could close that gap. :)

**Comment by plibither8** [comment]
Hi Jeff, thanks for the request! Seems to be a very reasonable request, and one that should be appreciate unanimously. I'll get to work on as soon as I get some time.

**Comment by plibither8** [comment]
Done! This might need some refinement in the future to cover edge-cases, but I guess it works well enough. I'll be pushing the changes to the marketplaces right now, but the Chrome extension might take some time to update.

Thanks once again!

**Comment by chris-morgan** [comment]
👎 I strongly believe that this should not be enabled by default, because it changes the meaning of text not uncommonly and is changing the meaning of Hacker News formatting. Immediately after #75 landed, I was talking about reStructuredText on a thread, which uses backticks in some places, and this *butchered* my comment.

It would be OK for Hacker News to introduce something like this—people will then work around it or not as the case may be—but so long as the rest of Hacker News is *not* treating backticks specially, it’s very bad for an extension to default to mangling content.

I suggest that this be disabled by default.

**Comment by plibither8** [comment]
Hi @chris-morgan, thanks for the comment. While I do understand your concern here, I won't be able to _disable default_: currently I have not worked up a mechanism to disable features by default. Once I do, I will surely look into this again.
