### ISSUE TITLE
[feature request] long show/hide bars on the left side of messages 

### ISSUE THREAD

**Issue by vanyakosmos** [plibither8/refined-hacker-news#79]
On reddit thread can be collapsed using vertical bar no matter how far above root message is. This feature will also help to determine "the level of nesting" of messages and will help to answer the question "is this message reply to the post or some other message?". 

<img width="406" alt="Screenshot 2020-06-25 at 21 14 34" src="https://user-images.githubusercontent.com/16745500/85775929-e82c1780-b728-11ea-8afc-dec9e8308291.png">

**Comment by plibither8** [comment]
Hi, thanks for opening the issue. I've thought about this a lot from the start, and implementing this currently would be next to impossible without giving the entire html DOM of the comments page a restructure. This is almost prohibitive because: 1) it'll take a lot of time to think, plan and implement such a solution, 2) it'll be very costly on the performance: changing almost the entire html content every time a comments page is opened will start to become annoying due to flashes of change being seen, and 3) it'll require changes in almost all other features.

For these reasons, I've decided not to implement it, it might be out of bounds for this extension.
